# Generated by Django 2.0.7 on 2018-07-14 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomelongo', models.CharField(max_length=80)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='Preço')),
                ('descricao', models.TextField(max_length=500)),
            ],
        ),
    ]
